name: ci

on:
  push:
    branches: [master]
    tags:
      - "v*"

jobs:
  test:
    name: 全量测试
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: 构建
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: "0"
        run: |
          mkdir -p dist/tools
          go build -ldflags="-s -w" -o dist/tools/demo ./cmd/demo
          cp data/builtin.bin dist/
          cp README.md LICENSE dist/
      - name: 打包
        run: |
          cd dist
          tar -czf ../nazhi-captcha-sdk-linux-amd64.tar.gz *
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-linux-amd64
          path: nazhi-captcha-sdk-linux-amd64.tar.gz

  publish:
    if: startsWith(github.ref, "refs/tags/v")
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: artifact-*
          path: dist
          merge-multiple: true
